random_seed: 42

train_dir: "data/train"
val_dir: "data/validation"
image_size: 140
train_test_split: 0.2
batch_size: 64
num_workers: 4
horizontal_flip: 0.5
vertical_flip: 0.5
pin_memory: true
persistent_workers: true
prefetch_factor: 2
